config/routes.rb
RedmineApp::Application.routes.draw do
  post '/custom_workflows/import', :to => 'custom_workflows#import', :as => 'import_custom_workflow'
  resources :custom_workflows
  post '/custom_workflows/:id', :to => 'custom_workflows#update'
  get '/custom_workflows/:id/export', :to => 'custom_workflows#export', :as => 'export_custom_workflow'
  post '/custom_workflows/:id/change_status', :to => 'custom_workflows#change_status', :as => 'custom_workflow_status'
end

app/models/custom_workflow.rb
class WorkflowError < StandardError
  attr_accessor :error

  def initialize(message)
    @error = message.dup
    super message
  end
end

class CustomWorkflow < ActiveRecord::Base
  OBSERVABLES = [:issue, :issue_attachments, :user, :attachment, :group, :group_users, :project, :project_attachments,
                 :wiki_content, :wiki_page_attachments, :shared]
  PROJECT_OBSERVABLES = [:issue, :issue_attachments, :project, :project_attachments, :wiki_content, :wiki_page_attachments]
  COLLECTION_OBSERVABLES = [:group_users, :issue_attachments, :project_attachments, :wiki_page_attachments]
  SINGLE_OBSERVABLES = [:issue, :user, :group, :attachment, :project, :wiki_content]

  attr_protected :id
  has_and_belongs_to_many :projects
  acts_as_list

  validates_presence_of :name
  validates_uniqueness_of :name, :case_sensitive => false
  validates_format_of :author, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, :allow_blank => true
  validate :validate_syntax, :validate_scripts_presence, :if => Proc.new {|workflow| workflow.respond_to?(:observable) and workflow.active?}

  if Rails::VERSION::MAJOR >= 4
    default_scope { order(:position => :asc) }
    projects_join_table = reflect_on_association(:projects).join_table
  else
    default_scope :order => 'position ASC'
    projects_join_table = reflect_on_association(:projects).options[:join_table]
  end

  scope :active, lambda { where(:active => true) }
  scope :for_project, (lambda do |project|
    where("is_for_all OR EXISTS (SELECT * FROM #{projects_join_table} WHERE project_id=? AND custom_workflow_id=id)", project.id)
  end)
  scope :observing, lambda { |observable| where(:observable => observable) }

  class << self
    def import_from_xml(xml)
      attributes = Hash.from_xml(xml).values.first
      attributes.delete('exported_at')
      attributes.delete('plugin_version')
      attributes.delete('ruby_version')
      attributes.delete('rails_version')
      CustomWorkflow.new(attributes)
    end

    def log_message(str, object)
      Rails.logger.info str + " for #{object.class} (\##{object.id}) \"#{object}\""
    end

    def run_shared_code(object)
      workflows = CustomWorkflow.observing(:shared).active
      log_message '= Running shared code', object
      workflows.each do |workflow|
        unless workflow.run(object, :shared_code)
          log_message '= Abort running shared code', object
          return false
        end
      end
      log_message '= Finished running shared code', object
      true
    end

    def run_custom_workflows(observable, object, event)
      workflows = CustomWorkflow.active.observing(observable)
      if PROJECT_OBSERVABLES.include? observable
        return true unless object.project
        workflows = workflows.for_project(object.project)
      end
      return true unless workflows.any?
      log_message "= Running #{event} custom workflows", object
      workflows.each do |workflow|
        unless workflow.run(object, event)
          log_message "= Abort running #{event} custom workflows", object
          return false
        end
      end
      log_message "= Finished running #{event} custom workflows", object
      true
    end
  end

  def run(object, event)
    return true unless attribute_present?(event)
    Rails.logger.info "== Running #{event} custom workflow \"#{name}\""
    object.instance_eval(read_attribute(event))
    true
  rescue WorkflowError => e
    Rails.logger.info "== User workflow error: #{e.message}"
    object.errors.add :base, e.error
    false
  rescue Exception => e
    Rails.logger.error "== Custom workflow exception: #{e.message}\n #{e.backtrace.join("\n ")}"
    object.errors.add :base, :custom_workflow_error
    false
  end

  def has_projects_association?
    PROJECT_OBSERVABLES.include? observable.to_sym
  end

  def validate_syntax_for(object, event)
    object.instance_eval(read_attribute(event)) if respond_to?(event) && read_attribute(event)
  rescue WorkflowError => e
  rescue Exception => e
    errors.add event, :invalid_script, :error => e
  end

  def validate_scripts_presence
    case observable.to_sym
      when :shared
        fields = [shared_code]
      when *SINGLE_OBSERVABLES
        fields = [before_save, after_save, before_destroy, after_destroy]
      when *COLLECTION_OBSERVABLES
        fields = [before_add, after_add, before_remove, after_remove]
      else
        fields = []
    end
    unless fields.any? {|field| field.present?}
      errors.add :base, :scripts_absent
    end
  end

  def validate_syntax
    case observable.to_sym
      when :shared
        CustomWorkflow.run_shared_code self
        validate_syntax_for self, :shared_code
      when *SINGLE_OBSERVABLES
        object = observable.camelize.constantize.new
        object.send :instance_variable_set, "@#{observable}", object # compatibility with 0.0.1
        CustomWorkflow.run_shared_code object
        [:before_save, :after_save, :before_destroy, :after_destroy].each {|field| validate_syntax_for object, field}
      when *COLLECTION_OBSERVABLES
        object = nil
        case observable.to_sym
          when :group_users
            object = Group.new
            object.send :instance_variable_set, :@user, User.new
            object.send :instance_variable_set, :@group, object
          when :issue_attachments
            object = Issue.new
            object.send :instance_variable_set, :@attachment, Attachment.new
            object.send :instance_variable_set, :@issue, object
          when :project_attachments
            object = Project.new
            object.send :instance_variable_set, :@attachment, Attachment.new
            object.send :instance_variable_set, :@project, object
          when :wiki_page_attachments
            object = WikiPage.new
            object.send :instance_variable_set, :@attachment, Attachment.new
            object.send :instance_variable_set, :@page, object
        end
        CustomWorkflow.run_shared_code self
        [:before_add, :after_add, :before_remove, :after_remove].each {|field| validate_syntax_for object, field}
    end
  end

  def export_as_xml
    only = [:author, :name, :description, :before_save, :after_save, :shared_code, :observable,
            :before_add, :after_add, :before_remove, :after_remove, :before_destroy, :after_destroy, :created_at]
    only = only.select { |p| self[p] }
    to_xml :only => only  do |xml|
      xml.tag! 'exported-at', Time.current.xmlschema
      xml.tag! 'plugin-version', Redmine::Plugin.find(:redmine_custom_workflows).version
      xml.tag! 'ruby-version', "#{RUBY_VERSION}-p#{RUBY_PATCHLEVEL}"
      xml.tag! 'rails-version', Rails::VERSION::STRING
    end
  end

  def <=>(other)
    self.position <=> other.position
  end

  def to_s
    name
  end
end

app/controllers/custom_workflows_controller.rb
class CustomWorkflowsController < ApplicationController

  layout 'admin'
  before_filter :require_admin
  before_filter :find_workflow, :only => [:show, :edit, :update, :destroy, :export, :change_status]

  def index
    @workflows = CustomWorkflow.includes(:projects).all
    respond_to do |format|
      format.html
    end
  end

  def export
    send_data @workflow.export_as_xml, :filename => @workflow.name + '.xml', :type => :xml
  end

  def show
    respond_to do |format|
      format.html { redirect_to edit_custom_workflow_path }
    end
  end

  def edit
  end

  def new
    @workflow = CustomWorkflow.new
    @workflow.author = cookies[:custom_workflows_author]
    respond_to do |format|
      format.html
    end
  end

  def import
    xml = params[:file].read
    begin
      @workflow = CustomWorkflow.import_from_xml(xml)
      @workflow.active = false
      if @workflow.save
        flash[:notice] = l(:notice_successful_import)
      else
        flash[:error] = @workflow.errors.full_messages.to_sentence
      end
    rescue Exception => e
      Rails.logger.warn "Workflow import error: #{e.message}\n #{e.backtrace.join("\n ")}"
      flash[:error] = l(:error_failed_import)
    end
    respond_to do |format|
      format.html { redirect_to(custom_workflows_path) }
    end
  end

  def create
    @workflow = CustomWorkflow.new(params[:custom_workflow])
    respond_to do |format|
      if params.has_key?(:commit) && @workflow.save
        flash[:notice] = l(:notice_successful_create)
        cookies[:custom_workflows_author] = @workflow.author
        format.html { redirect_to(custom_workflows_path) }
      else
        format.html { render :action => "new" }
      end
    end
  end

  def change_status
    respond_to do |format|
      if @workflow.update_attributes(:active => params[:active])
        flash[:notice] = l(:notice_successful_status_change)
        format.html { redirect_to(custom_workflows_path) }
      else
        format.html { render :action => :edit }
      end
    end
  end

  def update
    respond_to do |format|
      @workflow.assign_attributes(params[:custom_workflow])
      if params.has_key?(:commit) && @workflow.save
        flash[:notice] = l(:notice_successful_update)
        format.html { redirect_to(custom_workflows_path) }
      else
        format.html { render :action => :edit }
      end
    end
  end

  def destroy
    @workflow.destroy

    respond_to do |format|
      flash[:notice] = l(:notice_successful_delete)
      format.html { redirect_to(custom_workflows_path) }
    end
  end

  private

  def find_workflow
    @workflow = CustomWorkflow.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    render_404
  end

end

app/views/custom_workflows/_form.html.erb
<div class="splitcontent">
  <div class="splitcontentleft">
    <div class="box tabular">
      <p><%= f.text_field :name, :required => true, :size => 50 %></p>
      <p><%= f.text_field :author, :size => 50, :label => :field_custom_workflow_author %>
        <em class="info"><%= l(:text_custom_workflow_author) %></em>
      </p>
      <p><%= f.select :observable,
                      CustomWorkflow::OBSERVABLES.collect {|o| [l("custom_workflow_observable_#{o}"), o]}, {},
                      :onchange => 'this.form.submit()',
                      :disabled => !@workflow.new_record? %></p>
      <p><%= f.text_area :description, :cols => 40, :rows => 5 %></p>
      <% if @workflow.has_projects_association? %>
        <p><%= f.check_box :is_for_all, :onclick => "checkAndDisable('custom_workflow_enabled_projects', this.checked);", :label => :field_enabled_for_all_projects %></p>
      <% end %>
      <p><%= f.check_box :active, :label => :field_custom_workflow_active %></p>
    </div>
  </div>

  <% if @workflow.has_projects_association? %>
    <div class="splitcontentright">
      <fieldset class="box" id="custom_workflow_enabled_projects">
        <legend><%= l(:label_enabled_projects) %></legend>
        <%= custom_workflows_render_nested_projects(Project.visible.active) do |p|
          content_tag('label', check_box_tag('custom_workflow[project_ids][]', p.id, @workflow.project_ids.include?(p.id) || @workflow.is_for_all?,
                                             :id => nil, :disabled => @workflow.is_for_all?) + ' ' + h(p), :class => 'block')
        end %>
        <%= hidden_field_tag('custom_workflow[project_ids][]', '', :id => nil) %>
        <p><%= check_all_links 'custom_workflow_enabled_projects' %></p>
      </fieldset>
    </div>
  <% end %>
</div>

<div style="clear: left;"></div>

<fieldset class="box">
  <legend><%= l(:label_workflow_scripts) %></legend>
  <% observable = @workflow.observable.to_sym %>
  <p>
    <em class="info"><%= l("text_custom_workflow_#{observable}_code_note") %></em>
  </p>
  <% case observable %>
  <% when :shared %>
    <%= f.text_area :shared_code, :cols => 40, :rows => 20, :wrap => 'off', :class => 'custom_workflow_script' %>
  <% when *CustomWorkflow::COLLECTION_OBSERVABLES %>
    <%= render :layout => 'layouts/collapsible',
               :locals => {
                   :collapsed => (not (@workflow.before_add.present? or @workflow.after_add.present? or @workflow.errors[:base].present?)),
                   :label => l(:label_add_workflows)} do %>
      <div class="splitcontent">
        <div class="splitcontentleft">
          <%= f.text_area :before_add, :cols => 40, :rows => 20, :wrap => 'off', :class => 'custom_workflow_script' %>
        </div>
        <div class="splitcontentright">
          <%= f.text_area :after_add, :cols => 40, :rows => 20, :wrap => 'off', :class => 'custom_workflow_script' %>
        </div>
      </div>
    <% end %>
    <%= render :layout => 'layouts/collapsible',
               :locals => {
                   :collapsed => (not (@workflow.before_remove.present? or @workflow.after_remove.present?)),
                   :label => l(:label_remove_workflows)} do %>
      <div class="splitcontent">
        <div class="splitcontentleft">
          <%= f.text_area :before_remove, :cols => 40, :rows => 20, :wrap => 'off', :class => 'custom_workflow_script' %>
        </div>
        <div class="splitcontentright">
          <%= f.text_area :after_remove, :cols => 40, :rows => 20, :wrap => 'off', :class => 'custom_workflow_script' %>
        </div>
      </div>
    <% end %>
  <% when *CustomWorkflow::SINGLE_OBSERVABLES %>
    <%= render :layout => 'layouts/collapsible',
               :locals => {
                   :collapsed => (not (@workflow.before_save.present? or @workflow.after_save.present? or @workflow.errors[:base].present?)),
                   :label => l(:label_save_workflows)} do %>
      <div class="splitcontent">
        <div class="splitcontentleft">
          <%= f.text_area :before_save, :cols => 40, :rows => 20, :wrap => 'off', :class => 'custom_workflow_script' %>
          <% if observable == :issue %>
            <em class="info"><%= l(:text_custom_workflow_before_save_note) %></em>
          <% end %>
        </div>
        <div class="splitcontentright">
          <%= f.text_area :after_save, :cols => 40, :rows => 20, :wrap => 'off', :class => 'custom_workflow_script' %>
          <% if observable == :issue %>
            <em class="info"><%= l(:text_custom_workflow_after_save_note) %></em>
          <% end %>
        </div>
      </div>
    <% end %>
    <%= render :layout => 'layouts/collapsible',
               :locals => {
                   :collapsed => (not (@workflow.before_destroy.present? or @workflow.before_destroy.present?)),
                   :label => l(:label_destroy_workflows)} do %>
      <div class="splitcontent">
        <div class="splitcontentleft">
          <%= f.text_area :before_destroy, :cols => 40, :rows => 20, :wrap => 'off', :class => 'custom_workflow_script' %>
        </div>
        <div class="splitcontentright">
          <%= f.text_area :after_destroy, :cols => 40, :rows => 20, :wrap => 'off', :class => 'custom_workflow_script' %>
        </div>
      </div>
    <% end %>
  <% end %>
</fieldset>

<script type="text/javascript">
    jQuery('.custom_workflow_script').taboverride(2, true);
    function checkAndDisable(id, checked) {
        if (checked) {
            jQuery('#' + id).find('input[type=checkbox]').attr('checked', true).attr('disabled', true);
        } else {
            jQuery('#' + id).find('input[type=checkbox]').removeAttr('checked').removeAttr('disabled');
        }
    }
</script>

<%= wikitoolbar_for :custom_workflow_description %>

<% content_for :header_tags do %>
    <%= javascript_include_tag "tab_override", :plugin => 'redmine_custom_workflows' %>
<% end %>

app/views/custom_workflows/edit.html.erb
<h2><%= link_to l(:label_custom_workflow_plural), custom_workflows_path %> &#187; <%= @workflow %></h2>

<%= error_messages_for 'workflow' %>

<%= labelled_form_for @workflow do |f| %>
<%= render :partial => 'form', :locals => {:f => f} %>
<%= submit_tag l(:button_save) %>
<% end %>

<% html_title(l(:label_custom_workflow_plural), @workflow, l(:label_administration)) -%>

app/views/custom_workflows/index.html.erb
<% html_title(l(:label_custom_workflow_plural)) -%>
<div class="contextual">
  <%= link_to l(:label_custom_workflow_import), '#', :class => 'icon icon-import', :onclick => "showModal('import-dialog', '450px'); return false;" %>
  <%= link_to l(:label_custom_workflow_new), new_custom_workflow_path, :class => 'icon icon-add' %>
</div>

<h2><%=l(:label_custom_workflow_plural)%></h2>

<div class="autoscroll">
  <% if @workflows.any? %>
  <table class="custom-workflows list">
    <thead>
    <tr>
      <th><%= l(:field_name) %></th>
      <th><%= l(:field_description) %></th>
      <th><%= l(:field_observable) %></th>
      <th><%= l(:field_author) %></th>
      <th><%= l(:label_project_plural) %></th>
      <th><%= l(:button_sort) %></th>
      <th></th>
    </tr>
    </thead>
    <tbody>
    <% @workflows.each do |workflow| %>
    <tr class="<%= cycle("odd", "even") %> <%= 'disabled' unless workflow.active? %>">
      <td class="name"><%= link_to(workflow.name, edit_custom_workflow_path(workflow)) %></td>
      <td class="description"><%= textilizable(workflow.description) %></td>
      <td class="observable"><%= l("custom_workflow_observable_#{workflow.observable}") %></td>
      <td class="author"><%= mail_to workflow.author if workflow.author.present? %></td>
      <td>
        <% if not workflow.has_projects_association? %>
          -
        <% elsif workflow.is_for_all? %>
          <%= l(:field_enabled_for_all_projects) %>
        <% elsif workflow.projects.empty? %>
          <%= l(:text_no_enabled_projects) %>
        <% else %>
          <%= workflow.projects.map(&:name).join(", ") %>
        <% end %>
      </td>
      <td align="center" nowrap><%= reorder_links("custom_workflow", {:action => 'update', :id => workflow, :commit => true}) %></td>
      <td class="buttons">
        <% if workflow.active? %>
          <%= link_to(l(:button_custom_workflow_deactivate), custom_workflow_status_path(workflow, :active => false), :class => 'icon icon-inactive', :method => :post) %>
        <% else %>
          <%= link_to(l(:button_custom_workflow_activate), custom_workflow_status_path(workflow, :active => true), :class => 'icon icon-active', :method => :post) %>
        <% end %>
        <%= link_to(l(:label_custom_workflow_export), export_custom_workflow_path(workflow), :class => 'icon icon-export', :method => :get) %>
        <%= link_to(l(:button_delete), workflow, :class => 'icon icon-del', :data => {:confirm => l(:text_are_you_sure)}, :confirm => l(:text_are_you_sure), :method => :delete) %>
      </td>
    </tr>
    <% end %>
    </tbody>
  </table>
  <% else %>
    <p class="nodata"><%= l(:label_no_data) %></p>
  <% end %>
</div>

<div id="import-dialog" style="display: none">
  <h3 class="title"><%= l(:label_custom_workflow_import) %></h3>
  <%= form_tag import_custom_workflow_path, :multipart => true do %>
    <p>
      <%= l(:field_custom_workflow_file) %>:
    </p>

    <p>
      <%= file_field_tag 'file', :accept => 'application/xml' %>
    </p>

    <p class="buttons">
      <%= submit_tag l(:button_import), :name => nil, :onclick => "hideModal(this);" %>
      <%= submit_tag l(:button_cancel), :name => nil, :onclick => "hideModal(this);", :type => 'button' %>
    </p>
  <% end %>
</div>

app/views/custom_workflows/new.html.erb
<h2><%= link_to l(:label_custom_workflow_plural), custom_workflows_path %> &#187; <%= l(:label_custom_workflow_new) %></h2>

<%= error_messages_for 'workflow' %>

<%= labelled_form_for @workflow do |f| %>
<%= render :partial => 'form', :locals => {:f => f} %>
<%= submit_tag l(:button_create) %>
<% end %>

<% html_title(l(:label_custom_workflow_plural), l(:label_custom_workflow_new), l(:label_administration)) -%>